export const STATUS_CODES = {
  SUCCESS: 200,
  CREATED: 201,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  FORBIDDEN: 403,
  CONFLICT: 409,
  REQUIRED: 400,
  INTERNAL_SERVER_ERROR: 500,
  BAD_REQUEST: 400,
} as const;

export const TEXTS = {
  LOGIN: "Login Successfully!",
  INVALID_CREDENTIALS: "Invalid credentials!",
  INVALID_AUTH_TOKEN: "Invalid auth token!",
  NO_AUTH_GIVEN: "No auth given",
  REGISTERED_SUCCESS: "User registered successfully",
  EMAIL_ALREADY_EXISTS: "User with this email already exists",
  PHONE_ALREADY_EXISTS: "User with this phone number already exists",
  USER_NOT_FOUND: "User not found!",
  OTP_SENT: "Otp sent Successfully!",
  OTP_VERIFIED: "Otp verified Successfully!",
  INVALID_OTP: "Invalid Otp",
  PRODUCT_CREATED: "Product created successfully",
  PRODUCT_NOT_FOUND: "Product not found",
  PRODUCT_FETCHED: "Product fetched successfully",
  PRODUCTS_FETCHED: "Products fetched successfully",
  PRODUCT_UPDATED: "Product updated successfully",
  PRODUCT_DELETED: "Product deleted successfully",
  VARIANT_CREATED: "Product variant created successfully",
  VARIANT_NOT_FOUND: "Product variant not found",
  VARIANT_FETCHED: "Product variant fetched successfully",
  VARIANTS_FETCHED: "Product variants fetched successfully",
  VARIANT_UPDATED: "Product variant updated successfully",
  VARIANT_DELETED: "Product variant deleted successfully",
} as const;

